imports

In [ ]:

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn import svm
from sklearn.metrics import confusion_matrix

Data set

In [ ]:
df=pd.read_csv("parkison_data.csv")
#Target variable from file is status value 1 represents positive, 0 represents negative
X=df.drop(columns=["name","status"])
Y=df["status"]
#training Dataset
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=3)
#reducing range of features
sc=StandardScaler()
sc.fit(X_train)
X_train=sc.transform(X_train)
X_test=sc.transform(X_test)
#training the data using algo
sv=svm.SVC(kernel="linear")
sv.fit(X_train,Y_train)

X_pred_test=sv.predict(X_test)
acc=accuracy_score(Y_test,X_pred_test)
print("Accuracy of test svm is",acc)
X_pred_train=sv.predict(X_train)
acc=accuracy_score(Y_train,X_pred_train)
print("Accuracy of training in svm is",acc)
conf_matrix = confusion_matrix(Y_test, X_pred_test)

print("Confusion Matrix:")
print(conf_matrix)


Accuracy of test svm is 0.9230769230769231
Accuracy of training in svm is 0.8782051282051282
Confusion Matrix:
[[ 6  1]
 [ 2 30]]


In [ ]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(X_train, Y_train)
DT_test = clf.predict(X_test)
accuracy = clf.score(X_test, Y_test)
print("Accuracy of Decision Tree on test:", accuracy)
X_pred_train=clf.predict(X_train)
acc=accuracy_score(Y_train,X_pred_train)
print("Accuracy of training in clf is",acc)
conf_matrix = confusion_matrix(Y_test, DT_test)

print("Confusion Matrix:")
print(conf_matrix)


Accuracy of Decision Tree on test: 0.8461538461538461
Accuracy of training in clf is 1.0
Confusion Matrix:
[[ 6  1]
 [ 5 27]]


In [ ]:
#random_forest
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train, Y_train)
rf_test = rf.predict(X_test)
accuracy = rf.score(X_test, Y_test)
print("Accuracy of random forest on test:", accuracy)
X_pred_train=rf.predict(X_train)
acc=accuracy_score(Y_train,X_pred_train)
print("Accuracy of training in Random forest is",acc)
conf_matrix = confusion_matrix(Y_test, rf_test)

print("Confusion Matrix:")
print(conf_matrix)


Accuracy of random forest on test: 0.9230769230769231
Accuracy of training in Random forest is 1.0
Confusion Matrix:
[[ 5  2]
 [ 1 31]]


In [ ]:
#KNN Classifier
from sklearn.neighbors import KNeighborsClassifier
k = KNeighborsClassifier()
k.fit(X_train, Y_train)
k_test = k.predict(X_test)
accuracy = k.score(X_test, Y_test)
print("Accuracy of knn on test:", accuracy)
X_pred_train=k.predict(X_train)
acc=accuracy_score(Y_train,X_pred_train)
print("Accuracy of training in KNN is",acc)
conf_matrix = confusion_matrix(Y_test, k_test)

print("Confusion Matrix:")
print(conf_matrix)

Accuracy of knn on test: 0.8461538461538461
Accuracy of training in KNN is 0.9615384615384616
Confusion Matrix:
[[ 5  2]
 [ 4 28]]


In [ ]:
import xgboost as xgb
# Create DMatrix objects for training and testing
dtrain = xgb.DMatrix(X_train, label=Y_train)
dtest = xgb.DMatrix(X_test, label=Y_test)

# Define parameters for XGBoost
params = {
    'objective': 'binary:logistic',  # Classification task with binary labels
    'max_depth': 3,  # Maximum depth of each tree
    'eta': 0.1,  # Learning rate
    'eval_metric': 'error'  # Evaluation metric
}

# Training the XGBoost model
num_rounds = 100  # Number of boosting rounds (trees)
xg_model = xgb.train(params, dtrain, num_rounds)

# Making predictions on the testing set
xg_test = xg_model.predict(dtest)
xg_test = [round(pred) for pred in xg_test]  # Convert probabilities to binary labels

# Calculating accuracy
accuracy = accuracy_score(Y_test, xg_test)
print("Accuracy of XGBoost on test:", accuracy)

# Making predictions on the training set
xg_train = xg_model.predict(dtrain)
xg_train = [round(pred) for pred in xg_train]  # Convert probabilities to binary labels

# Calculating accuracy on training set
acc = accuracy_score(Y_train, xg_train)
print("Accuracy of XGBoost on training:", acc)

# Confusion matrix
conf_matrix = confusion_matrix(Y_test, xg_test)
print("Confusion Matrix:")
print(conf_matrix)


Accuracy of XGBoost on test: 0.9487179487179487
Accuracy of XGBoost on training: 1.0
Confusion Matrix:
[[ 5  2]
 [ 0 32]]


Model evaluation

In [ ]:
#taking one random data from our data set and predicting its value  first one is negative and remaiining all are positive
data = [
    [237.323, 243.709, 229.256, 0.00303, 0.00001, 0.00173, 0.00159, 0.00519, 0.01242, 0.116, 0.00696, 0.00747, 0.00882, 0.02089, 0.00533, 24.679, 0.384868, 0.62671, -7.018057, 0.176316, 1.852402, 0.091604],
    [223.361, 263.872, 87.638, 0.00352, 0.00002, 0.00169, 0.00188, 0.00506, 0.02536, 0.225, 0.01379, 0.01478, 0.01909, 0.04137, 0.01493, 20.366, 0.566849, 0.574282, -5.456811, 0.345238, 2.840556, 0.232861],
    [169.774,191.759,151.451,0.01568,0.00009,0.00863,0.00946,0.02589,0.08143,0.821,0.03804,0.05426,0.08808,0.11411,0.0753,12.359,0.56161,0.793509,-3.297668,0.414758,3.413649,0.457533],
[183.52,216.814,161.34,0.01466,0.00008,0.00849,0.00819,0.02546,0.0605,0.618,0.02865,0.04101,0.06359,0.08595,0.06057,14.367,0.478024,0.768974,-4.276605,0.355736,3.142364,0.336085],
[188.62,216.302,165.982,0.01719,0.00009,0.00996,0.01027,0.02987,0.07118,0.722,0.03474,0.0458,0.06824,0.10422,0.08069,12.298,0.55287,0.764036,-3.377325,0.335357,3.274865,0.418646],
[202.632,565.74,177.258,0.01627,0.00008,0.00919,0.00963,0.02756,0.0717,0.833,0.03515,0.04265,0.0646,0.10546,0.07889,14.989,0.427627,0.775708,-4.892495,0.262281,2.910213,0.270173],
[186.695,211.961,149.442,0.01872,0.0001,0.01075,0.01154,0.03225,0.0583,0.784,0.02699,0.03714,0.06259,0.08096,0.10952,12.529,0.507826,0.762726,-4.484303,0.340256,2.958815,0.301487],
[192.818,224.429,168.793,0.03107,0.00016,0.018,0.01958,0.05401,0.11908,1.302,0.05647,0.0794,0.13778,0.16942,0.21713,8.441,0.625866,0.76832,-2.434031,0.450493,3.079221,0.527367],
[198.116,233.099,174.478,0.02714,0.00014,0.01568,0.01699,0.04705,0.08684,1.018,0.04284,0.05556,0.08318,0.12851,0.16265,9.449,0.584164,0.754449,-2.839756,0.356224,3.184027,0.454721],
]


# Use the StandardScaler to transform the input_data
std = sc.transform(data)

# predicting using trained svm model
prediction = x.predict(std)
n=0
while len(prediction):
  if prediction[n]==0:
    print("Negative\n")
  else:
    print("Positive \n")
  n+=1
  if n==len(prediction):
    break

Negative

Positive 

Positive 

Positive 

Positive 

Positive 

Positive 

Positive 

Positive 



/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [ ]:
import zipfile

# Path to the zip file
zip_file_path = 'data.zip'

# Directory where you want to extract the contents of the zip file
extract_to_directory = 'data/'

# Open the zip file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    # Extract all the contents to the specified directory
    zip_ref.extractall(extract_to_directory)

print("Zip file extracted successfully.")


Zip file extracted successfully.


In [ ]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from PIL import Image
import numpy as np

# Function to extract features from text files
def extract_features_from_text(text_file):
    try:
        with open(text_file, 'r') as file:
            text = file.read()
        feature1 = len(text)
        feature2 = text.lower().count('important')  # Convert text to lowercase
        return [feature1, feature2]
    except Exception as e:
        print(f"Error processing text file '{text_file}': {e}")
        return [None, None]

# Function to extract features from images
def extract_features_from_image(image_file):
    try:
        image = Image.open(image_file)
        feature1, feature2 = image.size
        return [feature1, feature2]
    except Exception as e:
        print(f"Error processing image '{image_file}': {e}")
        return [None, None]

# Load data from text files
control_folder = "data/hw_dataset/control/"
parkinson_folder = "data/hw_dataset/parkinson/"

control_files = [os.path.join(control_folder, f) for f in os.listdir(control_folder)]
parkinson_files = [os.path.join(parkinson_folder, f) for f in os.listdir(parkinson_folder)]

control_data = [extract_features_from_text(file) for file in control_files]
parkinson_data = [extract_features_from_text(file) for file in parkinson_files]

# Create DataFrame from text data
control_df = pd.DataFrame(control_data, columns=["Text_Feature1", "Text_Feature2"])
control_df["parkinsons"] = 0
parkinson_df = pd.DataFrame(parkinson_data, columns=["Text_Feature1", "Text_Feature2"])
parkinson_df["parkinsons"] = 1

# Combine control and Parkinson's data
merged_df = pd.concat([control_df, parkinson_df], ignore_index=True)

# Load data from images
dynamic_folder = "data/hw_drawings/Dynamic Spiral Test/"
static_folder = "data/hw_drawings/Static Spiral Test/"

dynamic_files = [os.path.join(dynamic_folder, f) for f in os.listdir(dynamic_folder)]
static_files = [os.path.join(static_folder, f) for f in os.listdir(static_folder)]

dynamic_data = [extract_features_from_image(file) for file in dynamic_files]
static_data = [extract_features_from_image(file) for file in static_files]

# Combine image features
image_features = dynamic_data + static_data

# Ensure the number of image features matches the number of rows in the DataFrame
if len(image_features) != len(merged_df):
    if len(image_features) > len(merged_df):
        image_features = image_features[:len(merged_df)]
    else:
        num_features_to_pad = len(merged_df) - len(image_features)
        placeholder_value = [np.nan, np.nan]
        image_features += [placeholder_value] * num_features_to_pad

# Add image features to DataFrame
merged_df["Image_Feature1"] = [feat[0] for feat in image_features]
merged_df["Image_Feature2"] = [feat[1] for feat in image_features]

# Drop rows with any NaN values
merged_df.dropna(inplace=True)

# Split features and target variable
X = merged_df.drop(columns=["parkinsons"])
y = merged_df["parkinsons"]

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define classifiers with tuned hyperparameters
svm_clf = SVC(kernel='rbf', C=10, gamma='auto')
nb_clf = GaussianNB()
log_reg_clf = LogisticRegression(C=1, solver='liblinear')

# Train and evaluate classifiers
classifiers = {"SVM": svm_clf, "Naive Bayes": nb_clf, "Logistic Regression": log_reg_clf}
results = {}

for name, clf in classifiers.items():
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    results[name] = accuracy

# Print results
for name, accuracy in results.items():
    print(f"{name} Accuracy: {accuracy}")

# Choose the best classifier
best_classifier = max(results, key=results.get)
print(f"Best Classifier: {best_classifier}")


SVM Accuracy: 0.75
Naive Bayes Accuracy: 0.75
Logistic Regression Accuracy: 0.75
Best Classifier: SVM
